export interface IIndicador1 {
        zona: string,
        provincia: string,
        distrito: string,
        establecimiento: string,
        fecha: string,
        mes: string,
        responsable: string,
        fonendoscopio: string,
        tensiometro: string,
        cinta: string,
        balanza: string,
        termometro: string,
        promedio: string,

        lavado: string,
        basureros: string,
        fonendoscopioGine: string,
        tensiometroGine: string,
        termometroGine: string,
        lampara: string,
        camilla: string,
        corneta: string,
        cintaGine: string,
        papelera: string,
        guantes: string,
        soluciones: string,
        tirillas: string,
        especulos: string,
        espatulas: string,
        solucionesGine: string,
        hierro: string,
        promedioGine: string,

        numerador: string,
        denominador: string,
        promedioGeneral: string,

  }
  
  export interface INewIndicador1 {
  
    zona: string  | any,
    provincia: string  | any,
    distrito: string  | any,
    establecimiento: string  | any,
    fecha: string  | any,
    mes: string  | any,
    responsable: string  | any,
    fonendoscopio: string  | any,
    tensiometro: string  | any,
    cinta: string  | any,
    balanza: string  | any,
    termometro: string  | any,
    promedio: string  | any,

    lavado: string  | any,
    basureros: string  | any,
    fonendoscopioGine: string  | any,
    tensiometroGine: string  | any,
    termometroGine: string  | any,
    lampara: string  | any,
    camilla: string  | any,
    corneta: string  | any,
    cintaGine: string  | any,
    papelera: string  | any,
    guantes: string  | any,
    soluciones: string  | any,
    tirillas: string  | any,
    especulos: string  | any,
    espatulas: string  | any,
    solucionesGine: string  | any,
    hierro: string  | any,
    promedioGine: string  | any,

    numerador: string  | any,
    denominador: string  | any,
    promedioGeneral: string  | any,
  }